// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RowingLookbook_backend.Models;

namespace RowingLookbook_backend.Migrations
{
    [DbContext(typeof(LogBookContext))]
    partial class LogBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("RowingLookbook_backend.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("RowingLookbook_backend.Models.Tour", b =>
                {
                    b.Property<int>("TourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoatDriverID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoatID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberEight")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberFive")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberFour")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberNine")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberSeven")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberSix")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberThree")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TourStartplace")
                        .HasColumnType("TEXT");

                    b.Property<string>("TourStopplace")
                        .HasColumnType("TEXT");

                    b.HasKey("TourID");

                    b.ToTable("TourStarted");
                });
#pragma warning restore 612, 618
        }
    }
}
